build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-ble-beacon"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-net-echo-client"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-subsys-nvs"


install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: platformio platform install https://github.com/OS-Q/P41.git

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%

